//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sven.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Connect {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Connect() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sven.Resources.Pages.Connect", typeof(Connect).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        public static string BtnResendCode {
            get {
                return ResourceManager.GetString("BtnResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend reset link.
        /// </summary>
        public static string BtnResendResetLink {
            get {
                return ResourceManager.GetString("BtnResendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string BtnSignUp {
            get {
                return ResourceManager.GetString("BtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code.
        /// </summary>
        public static string BtnVerifyCode {
            get {
                return ResourceManager.GetString("BtnVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the instructions in email to complete password reset..
        /// </summary>
        public static string CodeSent_MsgLine1 {
            get {
                return ResourceManager.GetString("CodeSent_MsgLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes email ends up in spam folder, if you didn&apos;t received it try resending.
        /// </summary>
        public static string CodeSent_MsgLine2 {
            get {
                return ResourceManager.GetString("CodeSent_MsgLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email with reset link was sent to.
        /// </summary>
        public static string CodeSent_MsgMain {
            get {
                return ResourceManager.GetString("CodeSent_MsgMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully reset.
        /// </summary>
        public static string ForgotSignUp_MsgFinal {
            get {
                return ResourceManager.GetString("ForgotSignUp_MsgFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now sign in with your new password..
        /// </summary>
        public static string ForgotSignUp_MsgLine1 {
            get {
                return ResourceManager.GetString("ForgotSignUp_MsgLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your email and we&apos;ll send you a reset link.
        /// </summary>
        public static string ForgotSignUp_Subtitle {
            get {
                return ResourceManager.GetString("ForgotSignUp_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot the password?.
        /// </summary>
        public static string ForgotSignUp_Title {
            get {
                return ResourceManager.GetString("ForgotSignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? .
        /// </summary>
        public static string MsgAlreadyAccount {
            get {
                return ResourceManager.GetString("MsgAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string MsgForgotPassword {
            get {
                return ResourceManager.GetString("MsgForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a new code? .
        /// </summary>
        public static string MsgNeedNewCode {
            get {
                return ResourceManager.GetString("MsgNeedNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with.
        /// </summary>
        public static string MsgSignInWith {
            get {
                return ResourceManager.GetString("MsgSignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with.
        /// </summary>
        public static string MsgSignUpWith {
            get {
                return ResourceManager.GetString("MsgSignUpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string MsgWelcome {
            get {
                return ResourceManager.GetString("MsgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string PlainSignUp_Title {
            get {
                return ResourceManager.GetString("PlainSignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set the password for new account.
        /// </summary>
        public static string SetPassword_Msg {
            get {
                return ResourceManager.GetString("SetPassword_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the verification code from the email in your inbox or spam folder sent to.
        /// </summary>
        public static string VerifyCode_Msg {
            get {
                return ResourceManager.GetString("VerifyCode_Msg", resourceCulture);
            }
        }
    }
}
