<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Sven</RootNamespace>
    <UserSecretsId>84fc99e2-8226-40a7-b3ae-cbe5ad97935b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JavaScriptEngineSwitcher.Extensions.MsDependencyInjection" Version="3.24.1" />
    <PackageReference Include="JavaScriptEngineSwitcher.V8" Version="3.29.1" />
    <PackageReference Include="JavaScriptEngineSwitcher.V8.Native.win-x64" Version="3.29.0" />
    <PackageReference Include="LigerShark.WebOptimizer.Sass" Version="3.0.123" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="8.0.14" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bureau.AspNetCore\Bureau.AspNetCore.csproj" />
    <ProjectReference Include="..\Bureau.Server.Contracts\Bureau.Server.Contracts.csproj" />
    <ProjectReference Include="..\Sven\Sven.csproj" />
    <ProjectReference Include="..\Sven.Abstractions\Sven.Abstractions.csproj" />
    <ProjectReference Include="..\Sven.Contracts\Sven.Contracts.csproj" />
    <ProjectReference Include="..\Sven.Data.SqlServer\Sven.Data.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\scss\bootstrap\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Common.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Errors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Pages\Account.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Account.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Pages\Connect.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Connect.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Common.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Errors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\Account.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Account.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\Connect.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Connect.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
