# deploy/Dockerfile.chores
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release 
WORKDIR /src

COPY ["src/Niles.Chores.Api/Niles.Chores.Api.csproj", "src/Niles.Chores.Api/"]
RUN dotnet restore "./src/Niles.Chores.Api/Niles.Chores.Api.csproj"
COPY "src/Niles.Chores.Api/" "src/Niles.Chores.Api/"
WORKDIR "/src/src/Niles.Chores.Api"
RUN dotnet build "./Niles.Chores.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR "/src/src/Niles.Chores.Api"
RUN dotnet publish "./Niles.Chores.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=publish /app/publish ./

ENV ASPNETCORE_URLS=http://0.0.0.0:5000
EXPOSE 5000

ENTRYPOINT ["dotnet", "Niles.Chores.Api.dll"]