name: niles
version: "3.9"

services:
  niles-chores-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.chores.api
    container_name: niles-chores-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - nuc-network

  niles-chores-web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.chores.web
    container_name: niles-chores-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - nuc-network

networks:
  nuc-network:
    external: true
