<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bureau.Primitives\Bureau.Primitives.csproj" />
  </ItemGroup>

</Project>
