// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Watson.Nodes.Data.SqlServer.Contexts;

#nullable disable

namespace Watson.Nodes.Data.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerNodesContext))]
    partial class SqlServerNodesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Watson.Nodes.Models.NodeAttributeDb", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Locale")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("default");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("RefNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ValueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeId", "Key", "Locale");

                    b.HasIndex("Key", "Locale", "RefNodeId");

                    b.HasIndex("Key", "Locale", "ValueBool");

                    b.HasIndex("Key", "Locale", "ValueDate");

                    b.HasIndex("Key", "Locale", "ValueNumber");

                    b.HasIndex("NodeId", "Key", "Locale");

                    b.HasIndex("Key", "Locale", "Type", "NodeId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Key", "Locale", "Type", "NodeId"), new[] { "ValueString", "ValueJson" });

                    b.HasIndex("NodeId", "Key", "Locale", "OrderIndex");

                    b.ToTable("NodeAttributes", (string)null);
                });

            modelBuilder.Entity("Watson.Nodes.Models.NodeDb", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CreatedSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CreatedSequence"));

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.HasIndex("Kind", "Scope", "CanonicalKey")
                        .IsUnique()
                        .HasFilter("[CanonicalKey] IS NOT NULL");

                    b.HasIndex("Kind", "Scope", "CreatedSequence");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("Watson.Nodes.Models.NodeEdgeDb", b =>
                {
                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SourceNodeId", "TargetNodeId", "Purpose");

                    b.HasIndex("SourceNodeId", "Purpose");

                    b.HasIndex("TargetNodeId", "Purpose");

                    b.ToTable("NodeEdges", (string)null);
                });

            modelBuilder.Entity("Watson.Nodes.Models.NodeAttributeDb", b =>
                {
                    b.HasOne("Watson.Nodes.Models.NodeDb", "Node")
                        .WithMany("NodeAttributes")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Watson.Nodes.Models.NodeEdgeDb", b =>
                {
                    b.HasOne("Watson.Nodes.Models.NodeDb", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Watson.Nodes.Models.NodeDb", "TargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("Watson.Nodes.Models.NodeDb", b =>
                {
                    b.Navigation("NodeAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
