server {
    listen 80;
    server_name chores.devl.local;

    # LAN-only
    allow 192.168.0.0/16;
    deny all;

    # docker services on nuc-network
    set $chores_api  http://niles-chores-api:5000;
    set $chores_web  http://niles-chores-web:5000;

    location / {
        proxy_pass         $chores_web;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass         $chores_api;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
